dataset_path: sy1998/MLVU_dev
dataset_kwargs:
  token: true
generation_kwargs:
  max_new_tokens: 16
  temperature: 0
  top_p: 1.0
  num_beams: 1
  do_sample: false
task: molmo2_mlvu_dev
test_split: test
output_type: generate_until
doc_to_visual: !function utils.molmo2_mlvu_doc_to_visual_dev
doc_to_text: !function utils.mlvu_doc_to_text
doc_to_target: answer
process_results: !function utils.mlvu_process_results
process_docs: !function utils.molmo2_mlvu_process_docs
metric_list:
  - metric: mlvu_percetion_score
    aggregation: !function utils.mlvu_aggregate_results_dev
    higher_is_better: true
lmms_eval_specific_kwargs:
  default:
    pre_prompt: ""
    post_prompt: "\nOnly give the best option.\nBest option: ("
